from langchain_huggingface import HuggingFaceEmbeddings
from langchain_milvus import Milvus
from pydantic_ai.models.ollama import OllamaModel
from typing import Any
from pydantic import BaseModel
from pydantic_ai import Agent, AgentRunResult, RunContext


class RagDeps(BaseModel):
    """Dependencies injected into the Agent at runtime.

    Includes the vector store retriever.
    """
    class Config:
        arbitrary_types_allowed = True
    retriever: Any


class RagSearch:
    def __init__(self, milvus_uri: str, device: str, collection_name: str):
        """Initialize the RagSearch class.

        Args:
            milvus_uri (str): URI for the Milvus database.
            device (str): Device to use for embeddings, e.g., 'cuda' or 'cpu'.
            collection_name (str): Name of the Milvus collection to store vectors.
        """
        self.collection_name: str = collection_name
        self.milvus_uri: str = milvus_uri
        self.device: Any = device
        self.agent: Agent | None = None
        self.embeddings_generator: Any = None


    def get_embeddings_model(self, embed_model_name: str) -> Any:
        """Download and initialize the HuggingFace embeddings model.

        Returns:
            HuggingFaceEmbeddings: An instance of HuggingFaceEmbeddings with the specified model.
        """
        if self.embeddings_generator is None:
            self.embeddings_generator = HuggingFaceEmbeddings(
                model_name=embed_model_name)
        return self.embeddings_generator


    def get_retriever(self) -> Any:
        """Create a Milvus vectorstore retriever using LangChain and return it.

        Args:
            uri (str): URI for the Milvus database.
            embeddings (SentenceTransformerEmbeddings): Embedding function to use.
            collection_name (str): Name of the Milvus collection.
            k (int): Number of top results to return.

        Returns:
            Any: A retriever object that can be used to query the Milvus vectorstore.
        """
        vectorstore = Milvus(
            embedding_function=self.embeddings_generator,
            collection_name=self.collection_name,
            connection_args={
                "uri": self.milvus_uri,
            },
            text_field="chunk",
        )
        top_k: int = 5
        return vectorstore.as_retriever(search_kwargs={"k": top_k})


    def setup_agent(self, model_name: str = "qwen2.5:1.5b") -> None:
        """Initialize the Pydantic AI agent and define its tools.

        Args:
            model_name (str): Name of the Ollama model to use.

        Returns:
            None
        """
        model = OllamaModel(model_name=model_name)
        self.agent = Agent(
            model=model,
            deps_type=RagDeps,
            system_prompt=(
                 "You are a helpful assistant. Answer questions by retrieving relevant "
                    "context using the retrieve_notes tool. Be clear and concise."
            )
        )

        @self.agent.tool
        def retrieve_notes(ctx: RunContext[RagDeps], query: str) -> str:
            docs = ctx.deps.retriever.invoke(query)
            return "\n\n".join([doc.page_content for doc in docs])


    async def perform_rag_query(self, retriever: Any, query: str) -> str:
        """Perform a RAG query using the agent and the provided retriever.

        Args:
            retriever (Any): The retriever object to use for fetching relevant documents.
            query (str): The query string to search for.

        Returns:
            str: The response generated by the agent based on the retrieved documents.
        """
        if self.agent is None:
            raise ValueError("Agent is not initialized. Call setup_agent() first.")

        deps = RagDeps(retriever=retriever)
        result: AgentRunResult[str] = await self.agent.run(query, deps=deps)
        return result.data